### PR TITLE
Close leaked FDs

### LINKED ISSUE #10: cvmfs-x509-helper leaks two FDs per fetch
It appears the two FDs here are never closed:

https://github.com/cvmfs-contrib/cvmfs-x509-helper/blob/master/src/x509_helper_fetch.cc#L119

The leaked FDs pile up until, eventually, the helper is not able to open new files in proc - resulting in a failure to authorize.  The admin then has to remount the entire repository to recover access.

### PR DESCRIPTION
**Pull request by bbockelm**
Fix #10. 

Tested locally on a RHEL6 host.

### CODE REVIEW

**Comment by tpdownes** [comment]
@bbockelm any chance that this would manifest as a ~1% failure rate when rsync'ing a X509-protected CVMFS filesystem? e.g. something like this
```
rsync -av --delete --exclude=".cvmfscatalog" /cvmfs/ligo.osgstorage.org/frames/O2/hoft_C02_clean/ /bulk/O2/hoft_C02_clean/
```
would fail at about 1% rate (randomly, with successes following failures) and require several successive runs to complete.

**Comment by bbockelm** [comment]
Hi @tpdownes -

This problem left a pretty unique signature in syslog:

```
Jul  9 14:55:06 host.example.com cvmfs_x509_helper: (ligo.osgstorage.org) failed to open environment file for pid ${PID}.
```

If you see that, then this likely fixes the issue.  Additionally, once the mount entered this state, it stayed there until remount.

That said, my guess is you are seeing a problem with the data transfer itself.  Are there any messages from one of the cvmfs processes in syslog?

If it's a data transfer problem, I'll probably ask you to switch the config to a special debug server for verification on my side and we can debug from there.

Brian

**Comment by tpdownes** [comment]
My syslogs have rotated since my last real attempt at this, but I don't recall ever seeing that particular entry. The ones I've seen are more like [these](https://sft.its.cern.ch/jira/browse/CVM-1506?focusedCommentId=85092&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-85092):
```

Apr 11 10:41:13 execute0127 cvmfs2: (ligo.osgstorage.org) failed to fetch Part of /frames/O2/hoft_C02_clean/L1/L-L1_CLEANED_HOFT_C02-11853/L-L1_CLEANED_HOFT_C02-1185336405-4096.gwf (hash: 4f76321d5d1661c8deac2542615b3b62bb2dd687, error 7 [host connection problem])
--
Apr 11 10:42:22 execute0127 cvmfs2: (ligo.osgstorage.org) failed to fetch Part of /frames/O2/hoft_C02_clean/L1/L-L1_CLEANED_HOFT_C02-11853/L-L1_CLEANED_HOFT_C02-1185344597-4096.gwf (hash: da2bd162eade923c93852faf62b6c110292031de, error 9 [host returned HTTP error])
Apr 11 10:42:22 execute0127 cvmfs2: (ligo.osgstorage.org) switching host from https://xrootd-local.unl.edu:1094//user/ligo/ to https://its-condor-xrootd1.syr.edu:8443//user/ligo/
Apr 11 10:42:23 execute0127 cvmfs2: (ligo.osgstorage.org) failed to fetch Part of /frames/O2/hoft_C02_clean/L1/L-L1_CLEANED_HOFT_C02-11853/L-L1_CLEANED_HOFT_C02-1185344597-4096.gwf (hash: da2bd162eade923c93852faf62b6c110292031de, error 9 [host returned HTTP error])
Apr 11 10:42:23 execute0127 cvmfs2: (ligo.osgstorage.org) switching host from https://its-condor-xrootd1.syr.edu:8443//user/ligo/ to https://xrootd-local.unl.edu:1094//user/ligo/
Apr 11 10:42:23 execute0127 cvmfs2: (ligo.osgstorage.org) failed to fetch Part of /frames/O2/hoft_C02_clean/L1/L-L1_CLEANED_HOFT_C02-11853/L-L1_CLEANED_HOFT_C02-1185344597-4096.gwf (hash: da2bd162eade923c93852faf62b6c110292031de, error 9 [host returned HTTP error])
Apr 11 10:42:23 execute0127 cvmfs2: (ligo.osgstorage.org) switching host from https://xrootd-local.unl.edu:1094//user/ligo/ to https://its-condor-xrootd1.syr.edu:8443//user/ligo/
Apr 11 10:42:23 execute0127 cvmfs2: (ligo.osgstorage.org) failed to fetch Part of /frames/O2/hoft_C02_clean/L1/L-L1_CLEANED_HOFT_C02-11853/L-L1_CLEANED_HOFT_C02-1185344597-4096.gwf (hash: da2bd162eade923c93852faf62b6c110292031de, error 9 [host returned HTTP error])
```
For the failures, I believe it is true that Derek could not find corresponding log entries on the storage servers at UNL. My network engineer claimed and up and down that we are not hitting some traffic limit or NAT exhaustion on our side. So my favored theory was that some small fraction of the traffic is being blocked somewhere after UWM but before your storage servers.

I'm intentionally running without a cache but downloading 1 file at a time with `rsync`. Which should stress the infrastructure but I would presume to have a high success rate. If you tell me how to enable the debug server, I can setup a test rsync and document the outcome at a ticket of your choice.

**Comment by bbockelm** [comment]
Yeah - I would be more inclined to believe there are errors at UNL serving the data (`host returned HTTP error`) than a problem at the network side.

I would suggest:

1.  Try a fresh rsync on the default configs, confirm this problem still occurs.
2.  If you still see a 1% failure rate, try removing the `its-condor-xrootd1.syr.edu` endpoint from your config and replace `xrootd-local.unl.edu` with `red-gridftp12.unl.edu`.

**Comment by tpdownes** [comment]
Where best to report issue? The messages I quote above look pretty "CVMFS" rather than X509 related, but the infrastructure is different.

**Comment by bbockelm** [comment]
Let's use help@opensciencegrid.org; just make sure to CC me on the original email.

**Pull request merged**
