### PR TITLE
Add debug logging of authorization subject

### LINKED ISSUE #28: Show proxy DN and scitokens sub in debug log
It would be helpful if the x509 proxy DN and scitokens sub would be shown in the debug log.

### PR DESCRIPTION
**Pull request by DrDaveD**
This adds debug logging of x.509 proxy subjects and json web token sub claims.  Debug logging for the scitokens helper wasn't working at all, and this fixes that.

Fixes #28.

### CODE REVIEW

**Comment by djw8605** [comment]
Where does `SetLogAuthzDebugFile` get called?  By CVMFS itself?

**Comment by DrDaveD** [comment]
> Where does `SetLogAuthzDebugFile` get called? By CVMFS itself?

No, it's in the first line of CheckSciToken() in this PR.

**Comment by djw8605** [comment]
Ok, great!

**Review by djw8605 — APPROVED** [review]
LGTM

**Pull request merged**
